In [1]:
import pandas as pd
import numpy as np

In [2]:
games_df=pd.read_csv('./data/games.csv')  #主場和客場的總體數據
games_details_df=pd.read_csv('./data/games_details.csv')# 有上場球員的比賽詳細數據
players_df=pd.read_csv('./data/players.csv')# PLAYER_NAME|TEAM_ID|PLAYER_ID|SEASON
# TEAM_ID| LEAGUE_ID| SEASON_ID| STANDINGSDATE| CONFERENCE| TEAM| G| W| L| W_PCT| HOME_RECORD| ROAD_RECORD
ranking_df=pd.read_csv('./data/ranking.csv')
teams_df=pd.read_csv('./data/teams.csv') 
teams_name_df=pd.read_csv('./data/team_name_details.csv').drop(['Unnamed: 0'],axis=1)

In [3]:
sasId = teams_df.loc[teams_df['ABBREVIATION']=='SAS','TEAM_ID'].values[0]
type(sasId)

numpy.int64

In [4]:
# 兩年球員差異
def playerDiff(new,old):
    return list(set(old).difference(set(new))) 
# playerdiff_list = playerDiff(players2019,players2018)

In [5]:
all_year_list = players_df.loc[players_df['TEAM_ID']==sasId,'SEASON'].unique()

In [6]:
playerYesrDict = {}
for year in all_year_list:
    playerYesrDict['player'+str(year)] = list(players_df.loc[(players_df['TEAM_ID']==sasId)&(players_df['SEASON']==year),'PLAYER_ID'].unique())

In [7]:
# 每年的球員名單
playerYesrDict

{'player2019': [201942,
  200752,
  1627751,
  1628401,
  1627854,
  1627749,
  201988,
  1626168,
  1629234,
  201158,
  1629022,
  201960,
  1629002,
  200746,
  1629640,
  1629683,
  1629677,
  1629756,
  1629664],
 'player2018': [201942,
  200746,
  1627751,
  1627854,
  1628401,
  200752,
  201988,
  201158,
  202722,
  201967,
  202700,
  202347,
  1629022,
  1629234,
  1629002,
  2200,
  1627855,
  203910,
  203962,
  1627749,
  1628417],
 'player2017': [201980,
  200752,
  200746,
  201988,
  1627749,
  1938,
  203937,
  2200,
  2225,
  202722,
  1627854,
  203530,
  1628401,
  203464,
  1626199,
  1627856,
  202695,
  1628578,
  1628506],
 'player2016': [203613,
  1938,
  200746,
  201980,
  201988,
  203937,
  1627749,
  1627854,
  2200,
  203473,
  202722,
  201202,
  202695,
  101135,
  2225,
  1627879,
  1627868,
  1627853,
  203520],
 'player2015': [202695,
  200746,
  1495,
  201980,
  2225,
  201988,
  2561,
  1938,
  203937,
  2755,
  1626246,
  1889,
  2564,
  203613,
  2588,
  2446,
  203492,
  202130,
  202690,
  1626208,
  203472,
  1626304],
 'player2014': [202695,
  1495,
  201168,
  201980,
  2225,
  2564,
  1938,
  201988,
  201158,
  2588,
  201965,
  203382,
  202709,
  203937,
  202130,
  203210,
  201948,
  203955,
  204027],
 'player2013': [202695,
  1495,
  2564,
  201980,
  2225,
  1938,
  201168,
  201988,
  2588,
  201158,
  201965,
  202709,
  203382,
  201948,
  202345,
  200769,
  201986,
  201785,
  202952,
  203327,
  203587,
  1894,
  202408,
  203509],
 'player2012': [202695,
  1938,
  1495,
  201980,
  2225,
  202390,
  2564,
  201168,
  202709,
  201971,
  2588,
  201986,
  1503,
  201988,
  203382,
  1536,
  202341,
  2694,
  201974,
  2201,
  203178,
  203174],
 'player2011': [202695,
  1495,
  2564,
  1938,
  2225,
  1536,
  201168,
  202390,
  201980,
  201971,
  202341,
  2588,
  201988,
  202709,
  201182,
  202458,
  201286,
  2210,
  2551,
  202952,
  101113,
  202912,
  202371,
  202545,
  200852,
  201230,
  200779],
 'player2010': [2210,
  1495,
  686,
  1938,
  2225,
  201588,
  202390,
  201168,
  2588,
  201980,
  201971,
  200779,
  202341,
  200809,
  201785,
  202082,
  2137,
  202087,
  202066,
  2250,
  201998,
  201620,
  202408,
  2632],
 'player2009': [2210,
  686,
  1495,
  2225,
  1938,
  201588,
  2588,
  201971,
  2427,
  2586,
  101133,
  202066,
  201612,
  202132,
  714,
  689,
  2409,
  201998,
  201173,
  101204]}

In [8]:
# games_details_df.loc[games_details_df['TEAM_ID']==sasId]
all_year_list[0:6]

array([2019, 2018, 2017, 2016, 2015, 2014], dtype=int64)

In [9]:
sas_games_df = games_df.loc[(games_df['HOME_TEAM_ID']==sasId)|(games_df['VISITOR_TEAM_ID']==sasId)]

sasYearDF = {}

for year in all_year_list[0:6]:
    
    sasYearDF[str(year)+'df'] = sas_games_df.loc[(sas_games_df['SEASON'].isin(all_year_list[0:6]))&(sas_games_df['SEASON']==year)]

In [10]:
# 每年的sas比賽場次名單
for itemKey in sasYearDF.keys():
    print(itemKey)

2019df
2018df
2017df
2016df
2015df
2014df

In [11]:
# tag sas 贏
def tagSasWin(homeid,awayid,home_win):
    if homeid==sasId and home_win==1:

        return 1
    elif awayid==sasId and home_win==0:
        return 1
    else:
        return 0

In [12]:
sasYearDF['2019df']['isSASWin'] = sasYearDF['2019df'].apply(lambda x : tagSasWin(x['TEAM_ID_home'],x['TEAM_ID_away'],x['HOME_TEAM_WINS']), axis=1)
sasYearDF['2019df']

<ipython-input-12-eaec72556d66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sasYearDF['2019df']['isSASWin'] = sasYearDF['2019df'].apply(lambda x : tagSasWin(x['TEAM_ID_home'],x['TEAM_ID_away'],x['HOME_TEAM_WINS']), axis=1)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,isSASWin
13,2020-02-29,21900893,Final,1610612759,1610612753,2019,1610612759,114.0,0.524,0.750,...,31.0,1610612753,113.0,0.488,0.696,0.405,28.0,41.0,1,1
35,2020-02-26,21900869,Final,1610612759,1610612742,2019,1610612759,103.0,0.424,0.737,...,55.0,1610612742,109.0,0.419,0.667,0.378,25.0,43.0,0,0
57,2020-02-23,21900846,Final,1610612760,1610612759,2019,1610612760,131.0,0.575,0.875,...,54.0,1610612759,103.0,0.369,0.842,0.289,27.0,43.0,1,0
73,2020-02-21,21900832,Final,1610612762,1610612759,2019,1610612762,104.0,0.427,0.846,...,47.0,1610612759,113.0,0.440,0.885,0.500,22.0,48.0,0,1
98,2020-02-11,21900805,Final,1610612760,1610612759,2019,1610612760,106.0,0.459,0.810,...,35.0,1610612759,114.0,0.488,0.926,0.280,20.0,46.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16135,2019-10-18,11900078,Final,1610612759,1610612763,2019,1610612759,104.0,0.396,0.643,...,63.0,1610612763,91.0,0.344,0.769,0.200,20.0,57.0,1,1
16144,2019-10-16,11900064,Final,1610612745,1610612759,2019,1610612745,114.0,0.438,0.682,...,46.0,1610612759,128.0,0.571,0.636,0.370,29.0,43.0,0,1
16158,2019-10-13,11900048,Final,1610612759,1610612740,2019,1610612759,114.0,0.463,0.838,...,38.0,1610612740,123.0,0.489,0.767,0.333,26.0,45.0,0,0
16182,2019-10-08,11900019,Final,1610612748,1610612759,2019,1610612748,107.0,0.461,0.810,...,49.0,1610612759,89.0,0.400,0.808,0.308,21.0,37.0,1,0
16193,2019-10-05,11900007,Final,1610612759,1610612753,2019,1610612759,89.0,0.388,0.750,...,40.0,1610612753,125.0,0.526,0.714,0.361,29.0,47.0,0,0

In [13]:
# 勝場次底下的球賽
winGameList_2019 = sasYearDF['2019df'].loc[sasYearDF['2019df']['isSASWin']==1,'GAME_ID'].to_list()

In [14]:
winGameList_2019

[21900893,
 21900832,
 21900805,
 21900734,
 21900711,
 21900663,
 21900650,
 21900637,
 21900587,
 21900554,
 21900546,
 21900502,
 21900481,
 21900450,
 21900418,
 21900380,
 21900328,
 21900303,
 21900276,
 21900229,
 21900113,
 21900076,
 21900048,
 21900033,
 21900010,
 11900078,
 11900064]

In [15]:
# 贏局有出場的球員
games_details_df.loc[(games_details_df['GAME_ID'].isin(winGameList_2019))&(games_details_df['TEAM_ID']==sasId),'COMMENT'].unique()

array([nan, "DNP - Coach's Decision                  ",
       'DNP - Injury/Illness                    ',
       'DNP - Rest                              '], dtype=object)

In [16]:
# 贏局有出場的球員
games_details_df.loc[(games_details_df['GAME_ID'].isin(winGameList_2019))&(games_details_df['TEAM_ID']==sasId),'PLAYER_ID'].unique()

array([ 201942, 1626168, 1627751, 1627854, 1627749,  200752, 1628401,
        201988, 1629234, 1629022,  201158, 1629640, 1629677,  200746,
       1629002, 1629683,  201960, 1629756], dtype=int64)

In [17]:
games_details_df.loc[(games_details_df['GAME_ID'].isin(winGameList_2019))&(games_details_df['TEAM_ID']==sasId)]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
335,21900893,1610612759,SAS,San Antonio,201942,DeMar DeRozan,F,NaN,32:52,6.0,...,0.0,3.0,3.0,9.0,1.0,1.0,3.0,0.0,16.0,20.0
336,21900893,1610612759,SAS,San Antonio,1626168,Trey Lyles,F,NaN,39:48,8.0,...,0.0,9.0,9.0,2.0,4.0,1.0,1.0,3.0,20.0,14.0
337,21900893,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,C,NaN,4:14,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,9.0
338,21900893,1610612759,SAS,San Antonio,1627854,Bryn Forbes,G,NaN,23:43,5.0,...,0.0,1.0,1.0,1.0,0.0,0.0,3.0,2.0,13.0,7.0
339,21900893,1610612759,SAS,San Antonio,1627749,Dejounte Murray,G,NaN,30:23,7.0,...,0.0,2.0,2.0,7.0,3.0,1.0,4.0,1.0,15.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319728,11900064,1610612759,SAS,San Antonio,1629683,Quinndary Weatherspoon,NaN,NaN,7:09,0.0,...,0.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0,-10.0
319729,11900064,1610612759,SAS,San Antonio,1629756,Daulton Hommes,NaN,NaN,1:18,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
319730,11900064,1610612759,SAS,San Antonio,201942,DeMar DeRozan,NaN,DNP - Rest,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319731,11900064,1610612759,SAS,San Antonio,1629234,Drew Eubanks,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319732,11900064,1610612759,SAS,San Antonio,200752,Rudy Gay,NaN,DNP - Rest,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
games_details_df.loc[(games_details_df['GAME_ID'].isin(winGameList_2019))&(games_details_df['TEAM_ID']==sasId)].pivot(index ='GAME_ID', columns ='PLAYER_ID', values =['MIN'])

              MIN                                                          \
PLAYER_ID 200746  200752  201158  201942  201960  201988  1626168 1627749
GAME_ID
11900064    22:04     NaN   20:30     NaN   20:04   19:18   20:47   20:47
11900078    27:39   20:06   16:51   28:48   10:46   19:25   15:54   20:15
21900010    35:18   20:18   17:46   31:38     NaN   16:08   24:17   23:47
21900033    33:06   27:04   12:25   36:24     NaN   19:01   17:40   23:03
21900048    33:44   19:51   17:05   33:26     NaN   22:05   24:38   22:20
21900076    26:04   17:52   21:36   29:18   16:31   22:01   28:10     NaN
21900113    34:14   20:19   19:20   34:12    5:31   22:31   20:35   25:54
21900229    33:59   23:41   17:17   31:14   13:24   28:30   15:17     NaN
21900276    31:26   31:06   12:56   35:04     NaN   23:06   16:54   19:36
21900303      NaN   22:52     NaN   40:54    8:18   35:44   19:38   17:59
21900328    34:53   21:22   18:29   39:42     NaN   33:02   14:50   31:43
21900380    37:08   31:34    8:15   33:59     NaN   31:56   16:46   30:38
21900418    31:35   13:53   25:36   32:07     NaN   25:45   10:35   26:59
21900450    31:46   19:46   20:38   28:59    3:05   18:00   25:09   28:12
21900481    29:57   20:04    3:07   31:45     NaN   15:11   20:02   27:56
21900502    37:33   19:14   11:49   37:30     NaN   32:39   15:02   27:03
21900546    32:30   24:35     NaN   32:40    2:18   22:50   19:41   25:33
21900554    31:43   21:21    2:16   33:59    1:48   21:11   17:25   27:40
21900587    33:46   20:10   11:33   34:36     NaN   27:41   13:48   21:22
21900637    35:51     NaN   20:42   37:37     NaN   29:05   20:38   22:06
21900650    32:03     NaN   23:09   34:46     NaN   12:27   20:44   24:02
21900663    34:57    9:24   17:03   36:23     NaN   24:20   15:47   24:29
21900711      NaN   22:15   23:49   37:17     NaN   24:36   11:54   30:23
21900734    27:49    6:22   15:00   32:45     NaN   18:39   27:34   27:26
21900805    38:38   17:19   15:32     NaN     NaN   27:54   30:46   26:31
21900832    34:43   15:06     NaN   35:31     NaN   20:18   29:09   34:26
21900893      NaN   29:55    5:21   32:52     NaN   21:21   39:48   30:23

                                                                           \
PLAYER_ID 1627751 1627854 1628401 1629002 1629022 1629234 1629640 1629677
GAME_ID
11900064    18:47   22:09   20:04    7:09   22:57     NaN    9:48    7:09
11900078    16:25   20:49   19:08    3:56    8:10     NaN    3:56    3:56
21900010    16:07   32:31   22:10     NaN     NaN     NaN     NaN     NaN
21900033    14:49   32:02   19:32     NaN    4:56     NaN     NaN     NaN
21900048    12:06   29:05   25:40     NaN     NaN     NaN     NaN     NaN
21900076    18:07   26:24   25:59    3:49    2:11    1:58     NaN     NaN
21900113    12:53   22:32   20:13    0:53    0:53     NaN     NaN     NaN
21900229    23:54   20:06   25:17     NaN    7:21     NaN     NaN     NaN
21900276    15:30   23:50   28:24     NaN    1:04    1:04     NaN     NaN
21900303    41:10   36:35   25:41     NaN   34:53    6:16     NaN     NaN
21900328    18:07   19:38   21:17     NaN   11:57     NaN     NaN     NaN
21900380    15:52   15:47   21:47     NaN   21:18     NaN     NaN     NaN
21900418    15:37   21:51   21:01    0:48   14:13     NaN     NaN     NaN
21900450    12:43   24:52   19:48    3:31    3:31     NaN     NaN     NaN
21900481    22:50   29:42   20:04     NaN   16:15    3:07     NaN     NaN
21900502    15:22   31:28   26:18     NaN   11:04     NaN     NaN     NaN
21900546    12:46   25:10   20:09    2:18   19:30     NaN     NaN     NaN
21900554    14:01   26:49   20:18     NaN   19:13    2:16     NaN     NaN
21900587    19:35   20:19   26:38     NaN   10:32     NaN     NaN     NaN
21900637    12:09   16:09   25:54     NaN   19:49     NaN     NaN     NaN
21900650    15:55   32:45   26:36     NaN   17:34     NaN     NaN     NaN
21900663    13:03   23:40   27:26     NaN   13:28     NaN     NaN     NaN
21900711    22:25   23:05   22:54    6:00   15:23     NaN     NaN     NaN
21900734    18:14   16:25   26:36    1:57   19:16     NaN    1:57     NaN
21900805     9:18   21:21   27:54     NaN   24:48     NaN     NaN     NaN
21900832    13:17   25:26   19:35     NaN   12:29     NaN     NaN     NaN
21900893     4:14   23:43   25:20     NaN   10:33   16:30     NaN     NaN


PLAYER_ID 1629683 1629756
GAME_ID
11900064     7:09    1:18
11900078     3:56     NaN
21900010      NaN     NaN
21900033      NaN     NaN
21900048      NaN     NaN
21900076      NaN     NaN
21900113      NaN     NaN
21900229      NaN     NaN
21900276      NaN     NaN
21900303      NaN     NaN
21900328      NaN     NaN
21900380      NaN     NaN
21900418      NaN     NaN
21900450      NaN     NaN
21900481      NaN     NaN
21900502      NaN     NaN
21900546      NaN     NaN
21900554      NaN     NaN
21900587      NaN     NaN
21900637      NaN     NaN
21900650      NaN     NaN
21900663      NaN     NaN
21900711      NaN     NaN
21900734      NaN     NaN
21900805      NaN     NaN
21900832      NaN     NaN
21900893      NaN     NaN

In [19]:
# 針對2019年有贏場次出賽球員的戰鬥力分析
winGameThreeLayer_2019 = games_details_df.loc[(games_details_df['GAME_ID'].isin(winGameList_2019))&(games_details_df['TEAM_ID']==sasId)].set_index(['GAME_ID', 'PLAYER_ID', 'START_POSITION'])

In [20]:
winGameThreeLayer_2019

                                      TEAM_ID TEAM_ABBREVIATION    TEAM_CITY  \
GAME_ID  PLAYER_ID START_POSITION
21900893 201942    F               1610612759               SAS  San Antonio
         1626168   F               1610612759               SAS  San Antonio
         1627751   C               1610612759               SAS  San Antonio
         1627854   G               1610612759               SAS  San Antonio
         1627749   G               1610612759               SAS  San Antonio
...                                       ...               ...          ...
11900064 1629683   NaN             1610612759               SAS  San Antonio
         1629756   NaN             1610612759               SAS  San Antonio
         201942    NaN             1610612759               SAS  San Antonio
         1629234   NaN             1610612759               SAS  San Antonio
         200752    NaN             1610612759               SAS  San Antonio

                                              PLAYER_NAME  \
GAME_ID  PLAYER_ID START_POSITION
21900893 201942    F                        DeMar DeRozan
         1626168   F                           Trey Lyles
         1627751   C                         Jakob Poeltl
         1627854   G                          Bryn Forbes
         1627749   G                      Dejounte Murray
...                                                   ...
11900064 1629683   NaN             Quinndary Weatherspoon
         1629756   NaN                     Daulton Hommes
         201942    NaN                      DeMar DeRozan
         1629234   NaN                       Drew Eubanks
         200752    NaN                           Rudy Gay

                                                                    COMMENT  \
GAME_ID  PLAYER_ID START_POSITION
21900893 201942    F                                                    NaN
         1626168   F                                                    NaN
         1627751   C                                                    NaN
         1627854   G                                                    NaN
         1627749   G                                                    NaN
...                                                                     ...
11900064 1629683   NaN                                                  NaN
         1629756   NaN                                                  NaN
         201942    NaN             DNP - Rest
         1629234   NaN             DNP - Coach's Decision
         200752    NaN             DNP - Rest

                                     MIN  FGM   FGA  FG_PCT  FG3M  ...  OREB  \
GAME_ID  PLAYER_ID START_POSITION                                  ...
21900893 201942    F               32:52  6.0  13.0   0.462   0.0  ...   0.0
         1626168   F               39:48  8.0  13.0   0.615   2.0  ...   0.0
         1627751   C                4:14  0.0   0.0   0.000   0.0  ...   0.0
         1627854   G               23:43  5.0  11.0   0.455   3.0  ...   0.0
         1627749   G               30:23  7.0  10.0   0.700   1.0  ...   0.0
...                                  ...  ...   ...     ...   ...  ...   ...
11900064 1629683   NaN              7:09  0.0   1.0   0.000   0.0  ...   0.0
         1629756   NaN              1:18  0.0   0.0   0.000   0.0  ...   0.0
         201942    NaN               NaN  NaN   NaN     NaN   NaN  ...   NaN
         1629234   NaN               NaN  NaN   NaN     NaN   NaN  ...   NaN
         200752    NaN               NaN  NaN   NaN     NaN   NaN  ...   NaN

                                   DREB  REB  AST  STL  BLK   TO   PF   PTS  \
GAME_ID  PLAYER_ID START_POSITION
21900893 201942    F                3.0  3.0  9.0  1.0  1.0  3.0  0.0  16.0
         1626168   F                9.0  9.0  2.0  4.0  1.0  1.0  3.0  20.0
         1627751   C                0.0  0.0  1.0  0.0  0.0  1.0  1.0   0.0
         1627854   G                1.0  1.0  1.0  0.0  0.0  3.0  2.0  13.0
         1627749   G                2.0  2.0  7.0  3.0  1.0  4.0  1.0  15.0
...                                 ...  ...  ...  ...  ...  ...  ...   ...
11900064 1629683   NaN              0.0  0.0  2.0  1.0  0.0  2.0  1.0   0.0
         1629756   NaN              0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
         201942    NaN              NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
         1629234   NaN              NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
         200752    NaN              NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN

                                   PLUS_MINUS
GAME_ID  PLAYER_ID START_POSITION
21900893 201942    F                     20.0
         1626168   F                     14.0
         1627751   C                      9.0
         1627854   G                      7.0
         1627749   G                      0.0
...                                       ...
11900064 1629683   NaN                  -10.0
         1629756   NaN                    2.0
         201942    NaN                    NaN
         1629234   NaN                    NaN
         200752    NaN                    NaN

[361 rows x 25 columns]

In [21]:
# 算出平均上場時間

winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN'] = winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN'].str.replace(":",'.').replace(np.nan, 0).astype('float')
meanMIN = winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN'].values.mean()

C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2866: PerformanceWarning: indexing past lexsort depth may impact performance.
  result = self._run_cell(

In [22]:
meanMIN

18.27692307692308

In [27]:
winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN']= pd.to_numeric(winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN'], errors='coerce')

In [ ]:
winGameThreeLayer_2019.loc[(11900064,slice(None),slice(None)), :][winGameThreeLayer_2019['MIN']>meanMIN]

In [39]:
winGameThreeLayer_2019.loc[(21900893,slice(None),slice(None)), 'MIN'].apply(pd.to_numeric)

GAME_ID   PLAYER_ID  START_POSITION
21900893  201942     F                 32.52
          1626168    F                 39.48
          1627751    C                  4.14
          1627854    G                 23.43
          1627749    G                 30.23
          200752     NaN               29.55
          1628401    NaN               25.20
          201988     NaN               21.21
          1629234    NaN               16.30
          1629022    NaN               10.33
          201158     NaN                5.21
          1629640    NaN                0.00
          1629677    NaN                0.00
Name: MIN, dtype: float64

In [31]:
winGameThreeLayer_2019.index.levels[2]

Index(['C', 'F', 'G'], dtype='object', name='START_POSITION')

In [36]:
winGameThreeLayer_2019.columns.get_level_values(0)[5]

'MIN'

In [ ]:
games_details_df.columns

In [ ]:
{
    'GP':"出場數",
    "GS":"先發場數",
    "START_POSITION":"",
    "COMMENT":"",
    "MIN":"",
    "FGM":"投中次數",
    "FGA":"投籃次數",
    "FG_PCT":"命中率",
    "FG3M":"3分球命中次數",
    "FG3A":"3分球投籃次數",
    "FG3_PCT":"3分球命中率",
    "FTM":"罰球命中次數",
    "FTA":"罰球次數",
    "FT_PCT":"罰球率",
    "OREB":"進攻",
    "DREB":"防守籃板球",
    "REB":"籃板球",
    "AST":"助攻",
    "STL":"抄截",
    "BLK":"吃火鍋",
    "TO":"失誤",
    "PF":"個人犯規",
    "PTS":"得分",
    "PLUS_MINUS":"在場上時隊得分與失分差距",

}

In [ ]:
"""
GP, GS: games played, games started (出場數，先發場數)
PTS: points(得分)
+ / - : 在場上時隊得分與失分差距。=>例如，在得分平手時上場，打一陣子下場時，球隊贏10分，
FGM, FGA, FG%: field goals made, attempted and percentage(投中次數，投籃次數，百分比)
FTM, FTA, FT%: free throws made, attempted and percentage(罰球命中次數，罰球次數，百分比)
3FGM, 3FGA, 3FG%: three-point field goals made, attempted and percentage(3分球命中次數，出手次數，百分比)
REB, OREB, DREB: rebounds, offensive rebounds, defensive rebounds(籃板球，進攻，防守籃板球)
AST: assists(助攻)

STL: steals(抄截)

BLK: blocks(火鍋)

BA: (block against) 吃火鍋

BS: (blocked shots) 賞火鍋

TO: turnovers(失誤)
EFF: efficiency: NBA's efficiency rating: (PTS + REB + AST + STL + BLK - FG missed - FT missed - TO)

NBA效率 = (得分+籃板+助攻+抄截+火鍋 - 投籃失手 - 罰球失手 - 失誤)

PF: personal fouls(個人犯規)

MIN: minutes(上場分鐘數)

F - 前鋒
C - 中鋒
G - 後衛
G-F - 後衛型前鋒
F-G - 小前鋒
G - 上場次數
HI - 本賽季單場最高得分
MIN - 總出場時間
MPG - 每場得分
PF - 犯規次數
PPG - 平均得分
PTS - 總得分
ST - 搶斷
"""
games_details_df.columns

In [ ]:
# sas 主場 贏
sasYearDF['2019df']['SAS_WIn'] = sasYearDF['2019df'].loc[(sasYearDF['2019df']['TEAM_ID_home']==sasId)&(sasYearDF['2019df']['HOME_TEAM_WINS']==1)].apply(lambda x: 1 if 'ing' in x else 0)

In [ ]:
# sas 客座 贏
sasYearDF['2019df'].loc[(sasYearDF['2019df']['TEAM_ID_away']==sasId)&(sasYearDF['2019df']['HOME_TEAM_WINS']==0)]

In [ ]:
sasYearDF['2019df'].loc[(sasYearDF['2019df']['TEAM_ID_home']==sasId)&(sasYearDF['2019df']['HOME_TEAM_WINS']==0)]

In [ ]:
len(sasYearDF['2019df'].loc[sasYearDF['2019df']['isSASWin']==0])

In [ ]:
sasYearDF['2019df']